version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.19.2-browsers
        environment:
          TEST_DATABASE_URL: mongodb://root:example@mongo:27017
      - image: circleci/mongo:latest-ram
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: MongoDB Install
          command: sudo apt-get update && sudo apt-get install -y mongo
      - run:
          name: Install package json dependencies
          command: npm install   
      - run:
          name: Run test
          command: npm test      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build