version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.19.2-browsers
        environment:
          NODE_ENV: development
          TOKEN_SECRECT: 7d49614d503f18e6db7b47d4aed22948010762f9748cfb75da667b4e8c26036f9a7555b6a977e0757c6cf3d49bc7b93abaa628b3293dee6cd112226fe7f8ac1b
          REFRESH_TOKEN_SECRECT: 5017dff4db4e94550401c978acc1265c829bbca5a51a37f348a9e9f568383923ac96ffaff3b9f098bdce7781ff2aafba143e077a4ee0ab96576145967db1246a
  
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $DATABASE_URL # this env var must be set within the project
      - run: sudo apt-get update
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context:
            - mongo