version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: MongoDB Install
          command: sudo apt-get install -y mongodb
      - run:
          name: Database Setup
          command: mongodb && mongo --eval 'db.createUser({ user: "myrootuser", pwd: "mypassword", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] })' 
      - run:
          name: Install package json dependencies
          command: npm install   
      - run:
          name: Run test
          command: npm  test      
