version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.19.2-browsers
        environment:
          ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
          NODE_ENV: test
       # Service container image    
      - image: circleci/mongo:3.6.19-xenial
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          name: MongoDB Install
          command: sudo apt-get install -y mongodb
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build